---
version: "3"

services:

  db:
    image: demo-postgres
    user: "32767"
    volumes:
      - "/home/ec2-user/secrets:/mnt/secrets"
      - "demo-postgres:/var/lib/postgresql/data"

  web:
    image: app
    user: "32767"
    environment:
      PG_HOST: "db"
      PG_PORT: "5432"   
      IG_USER: "postgres"
      IG_PASSWORD_FILE: "/mnt/secrets/postgres-passwd"
      IG_DATABASE: "postgres"
    ports:
      - "8888:8888"
    volumes:
      - "/home/ec2-user/secrets:/mnt/secrets"
    depends_on:
      - "db" 


volumes:
  demo-postgres:
    external: yes